// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFBX-CWzPBBbOu6MOVFxtecH8l0FV0so',
    appId: '1:466932017871:web:cc753f855dbab5f083e5ba',
    messagingSenderId: '466932017871',
    projectId: 'hackula1',
    authDomain: 'hackula1.firebaseapp.com',
    storageBucket: 'hackula1.firebasestorage.app',
    measurementId: 'G-M5FV54NKDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_rtpM1xlFtzf8wyV_C60NbAL86TkH7w',
    appId: '1:466932017871:android:5f69069852926a3383e5ba',
    messagingSenderId: '466932017871',
    projectId: 'hackula1',
    storageBucket: 'hackula1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD264FCDhrx9c9QDzi4SKXSL0os8LAZm2o',
    appId: '1:466932017871:ios:bfc43f69d2a1cf5283e5ba',
    messagingSenderId: '466932017871',
    projectId: 'hackula1',
    storageBucket: 'hackula1.firebasestorage.app',
    iosBundleId: 'com.example.hackula1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD264FCDhrx9c9QDzi4SKXSL0os8LAZm2o',
    appId: '1:466932017871:ios:bfc43f69d2a1cf5283e5ba',
    messagingSenderId: '466932017871',
    projectId: 'hackula1',
    storageBucket: 'hackula1.firebasestorage.app',
    iosBundleId: 'com.example.hackula1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATFBX-CWzPBBbOu6MOVFxtecH8l0FV0so',
    appId: '1:466932017871:web:cf335e738847004283e5ba',
    messagingSenderId: '466932017871',
    projectId: 'hackula1',
    authDomain: 'hackula1.firebaseapp.com',
    storageBucket: 'hackula1.firebasestorage.app',
    measurementId: 'G-1F9LCMHWNR',
  );
}
